package com.upc.entity;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

// default package
// Generated 17-may-2018 13:26:54 by Hibernate Tools 5.3.0.Beta2

/**
 * Administrador generated by hbm2java
 */
@Entity
@Table(name = "administrador")
public class Administrador  {
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private int idadministrador;
	
	@ManyToOne
	@JoinColumn(name="idusuario")
	private Usuario usuario;
	
	private int telefono;
	private int celular;
	private String correo;
	private String descripcion;

	public Administrador() {
		super();
	}


	public Integer getIdadministrador() {
		return this.idadministrador;
	}

	public void setIdadministrador(Integer idadministrador) {
		this.idadministrador = idadministrador;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}


	public int getTelefono() {
		return this.telefono;
	}

	public void setTelefono(int telefono) {
		this.telefono = telefono;
	}

	public Integer getCelular() {
		return this.celular;
	}

	public void setCelular(Integer celular) {
		this.celular = celular;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
