package com.upc.entity;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

// default package
// Generated 17-may-2018 13:26:54 by Hibernate Tools 5.3.0.Beta2

/**
 * Comentario generated by hbm2java
 */
@Entity
@Table(name = "comentario")
public class Comentario {
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private int idcomentario;
	
	@ManyToOne
	@JoinColumn(name="idlista_empleado_solicitud")
	private ListaEmpleadoSolicitud listaEmpleadoSolicitud;
	private String titulo;
	private String imagen;
	private String descripcion;

	public Comentario() {
		super();
	}


	public Integer getIdcomentario() {
		return this.idcomentario;
	}

	public void setIdcomentario(Integer idcomentario) {
		this.idcomentario = idcomentario;
	}

	public ListaEmpleadoSolicitud getListaEmpleadoSolicitud() {
		return this.listaEmpleadoSolicitud;
	}

	public void setListaEmpleadoSolicitud(ListaEmpleadoSolicitud listaEmpleadoSolicitud) {
		this.listaEmpleadoSolicitud = listaEmpleadoSolicitud;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
