package com.upc.entity;

// default package
// Generated 17-may-2018 13:26:54 by Hibernate Tools 5.3.0.Beta2


import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ListaSucursal generated by hbm2java
 */
@Entity
@Table(name = "lista_sucursal")
public class ListaSucursal{
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private int idlistaSucursal;
	
	@ManyToOne
	@JoinColumn(name="idempresa")
	private Empresa empresa;
	
	@ManyToOne
	@JoinColumn(name="idciudad")
	private Ciudad ciudad;
	private String nombre;
	private String direccion;
	private String descripcion;


	public ListaSucursal() {
		super();
	}


	public Integer getIdlistaSucursal() {
		return this.idlistaSucursal;
	}

	public void setIdlistaSucursal(Integer idlistaSucursal) {
		this.idlistaSucursal = idlistaSucursal;
	}

	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	public Ciudad getCiudad() {
		return ciudad;
	}
	public void setCiudad(Ciudad ciudad) {
		this.ciudad = ciudad;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
