package com.upc.entity;

// default package
// Generated 17-may-2018 13:26:54 by Hibernate Tools 5.3.0.Beta2

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ListaEmpleadoSolicitud generated by hbm2java
 */
@Entity
@Table(name = "lista_empleado_solicitud")
public class ListaEmpleadoSolicitud {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private int idlistaEmpleadoSolicitud;
	
	@ManyToOne
	@JoinColumn(name="idplantilla")
	private Plantilla plantilla;
	
	@ManyToOne
	@JoinColumn(name="idsolicitud")
	private Solicitud solicitud;

	private String descripcion;


	public ListaEmpleadoSolicitud() {
		super();
	}


	public Integer getIdlistaEmpleadoSolicitud() {
		return this.idlistaEmpleadoSolicitud;
	}

	public void setIdlistaEmpleadoSolicitud(Integer idlistaEmpleadoSolicitud) {
		this.idlistaEmpleadoSolicitud = idlistaEmpleadoSolicitud;
	}

	public Plantilla getPlantilla() {
		return this.plantilla;
	}

	public void setPlantilla(Plantilla plantilla) {
		this.plantilla = plantilla;
	}

	public Solicitud getSolicitud() {
		return this.solicitud;
	}

	public void setSolicitud(Solicitud solicitud) {
		this.solicitud = solicitud;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}


}
