package com.upc.entity;

// default package
// Generated 17-may-2018 13:26:54 by Hibernate Tools 5.3.0.Beta2

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Plantilla generated by hbm2java
 */
@Entity
@Table(name = "plantilla")
public class Plantilla {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private int idplantilla;
	
	@ManyToOne
	@JoinColumn(name="idservicio")
	private Servicio servicio;
	
	@ManyToOne
	@JoinColumn(name="idlista_sucursal")
	private ListaSucursal listaSucursal;
	
	@ManyToOne
	@JoinColumn(name="idestado_validar")
	private EstadoValidar estadoValidar;
	
	private String descripcion;


	public Plantilla() {
		super();
	}


	public int getIdplantilla() {
		return idplantilla;
	}


	public void setIdplantilla(int idplantilla) {
		this.idplantilla = idplantilla;
	}


	public Servicio getServicio() {
		return servicio;
	}


	public void setServicio(Servicio servicio) {
		this.servicio = servicio;
	}


	public ListaSucursal getListaSucursal() {
		return listaSucursal;
	}


	public void setListaSucursal(ListaSucursal listaSucursal) {
		this.listaSucursal = listaSucursal;
	}


	public EstadoValidar getEstadoValidar() {
		return estadoValidar;
	}


	public void setEstadoValidar(EstadoValidar estadoValidar) {
		this.estadoValidar = estadoValidar;
	}


	public String getDescripcion() {
		return descripcion;
	}


	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
	
}
