package com.upc.entity;

import java.util.Date;

// default package
// Generated 17-may-2018 13:26:54 by Hibernate Tools 5.3.0.Beta2

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Solicitud generated by hbm2java
 */
@Entity
@Table(name = "solicitud")
public class Solicitud {
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private int idsolicitud;
	
	@ManyToOne
	@JoinColumn(name="idcliente")
	private Cliente cliente;
	
	@ManyToOne
	@JoinColumn(name="idestado_proceso")
	private EstadoProceso estadoProceso;

	@ManyToOne
	@JoinColumn(name="idestadovalidar_empresa")
	private EstadoValidar estadoValidarByIdestadovalidarEmpresa;
	
	@ManyToOne
	@JoinColumn(name="idestadovalidar_cliente")
	private EstadoValidar estadoValidarByIdestadovalidarCliente;
	private Date fechaSolicitado;
	private Date fechaAprobado;
	private Date fechaAtencion;
	private int calificacion;
	private String descripcion;


	public Solicitud() {
		super();
	}


	public Integer getIdsolicitud() {
		return this.idsolicitud;
	}

	public void setIdsolicitud(Integer idsolicitud) {
		this.idsolicitud = idsolicitud;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public EstadoProceso getEstadoProceso() {
		return this.estadoProceso;
	}

	public void setEstadoProceso(EstadoProceso estadoProceso) {
		this.estadoProceso = estadoProceso;
	}

	public EstadoValidar getEstadoValidarByIdestadovalidarEmpresa() {
		return this.estadoValidarByIdestadovalidarEmpresa;
	}

	public void setEstadoValidarByIdestadovalidarEmpresa(EstadoValidar estadoValidarByIdestadovalidarEmpresa) {
		this.estadoValidarByIdestadovalidarEmpresa = estadoValidarByIdestadovalidarEmpresa;
	}

	public EstadoValidar getEstadoValidarByIdestadovalidarCliente() {
		return this.estadoValidarByIdestadovalidarCliente;
	}

	public void setEstadoValidarByIdestadovalidarCliente(EstadoValidar estadoValidarByIdestadovalidarCliente) {
		this.estadoValidarByIdestadovalidarCliente = estadoValidarByIdestadovalidarCliente;
	}

	public Date getFechaSolicitado() {
		return this.fechaSolicitado;
	}

	public void setFechaSolicitado(Date fechaSolicitado) {
		this.fechaSolicitado = fechaSolicitado;
	}

	public Date getFechaAprobado() {
		return this.fechaAprobado;
	}

	public void setFechaAprobado(Date fechaAprobado) {
		this.fechaAprobado = fechaAprobado;
	}

	public Date getFechaAtencion() {
		return this.fechaAtencion;
	}

	public void setFechaAtencion(Date fechaAtencion) {
		this.fechaAtencion = fechaAtencion;
	}

	public Integer getCalificacion() {
		return this.calificacion;
	}

	public void setCalificacion(Integer calificacion) {
		this.calificacion = calificacion;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
