package com.upc.entity;

// default package
// Generated 17-may-2018 13:26:54 by Hibernate Tools 5.3.0.Beta2

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoEmpresa generated by hbm2java
 */
@Entity
@Table(name = "tipo_empresa")
public class TipoEmpresa {
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private int idtipoEmpresa;
	private String nombre;
	private String descripcion;

	public TipoEmpresa() {
		super();
	}

	public Integer getIdtipoEmpresa() {
		return this.idtipoEmpresa;
	}

	public void setIdtipoEmpresa(Integer idtipoEmpresa) {
		this.idtipoEmpresa = idtipoEmpresa;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}


}
